# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-91332049-1'

menu: 
  - name: Featured Projects
    submenu:
      - name: MicroBam
        link: /projects/microbam
      - name: OurLegacy
        link: /projects/ourlegacy
  - name: Posts
    link: /
  - name: Tags
    link: /tags
  - name: About
    link: /about
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/ngtranminhtuan
      - name: LinkedIn
        icon: linkedin-square
        link: https://www.linkedin.com/in/minh-tuan-nguyen-tran-3449a2137/
      - name: Youtube
        icon: youtube
        link: https://www.youtube.com/channel/UCIUUAjf2HV-TPXQwjVC0LzA/playlists
    
